default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: WARNING
  pool: 50
  timeout: 5000

development:
  <<: *default
  database: contact_list_development
  host: localhost
  username: devuser
  password: devuser

test:
  <<: *default
  database: contact_list_test
  host: localhost
  username: devuser
  password: devuser

production:
  <<: *default
  database: contact_list_production
  username: contact_list
  password: contact_list

